apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple-logging-ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simple-logging-ui.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "simple-logging-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "simple-logging-ui.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: GRPC_WEB_URL
              {{- if .Values.grpcWebUrl }}
              value: {{ .Values.grpcWebUrl | quote }}
              {{- else if and .Values.ingress.enabled .Values.ingress.host }}
              value: {{ printf "http://%s" .Values.ingress.host | quote }}
              {{- else }}
              value: "http://simple-logging:8080"
              {{- end }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
